apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: NodeJsToDoApp
  template:
    metadata:
      labels:
        app: NodeJsToDoApp
    spec:
      containers:
      - name: NodeJsToDoApp
        image: haizen12/nodejstodoapp:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
